on:
  push:
    branches: [ "master" ]
    
env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'


    - name: Setup pnpm and Install
      uses: seepine/action-setup-pnpm@v1
        
    - name: pnpm install, build
      run: |
        pnpm install
        pnpm run build
        
