name: github action workflow to build an app and push image to docker hub
on:
  push:
    branches: [ "master" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone git repository
      uses: actions/checkout@v4

    - name: build image
      run: docker build . -t ${{ secrets.DOCKERHUB_USER }}/github-action-test:latest

    - name: push image to docker hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USER }}/github-action-test:latest
        
